on: [push]

jobs:
  TCA_Scan:
    runs-on: ubuntu-latest
    name: TCA
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tencent Cloud Code Analysis
        uses: TCATools/TCA-action@main
        with:
          block: false
          label: open-source