on: [push]

jobs:
  TCA_Scan:
    runs-on: ubuntu-latest
    name: TCA
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get git diff files
        run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > changed.txt  && cat changed.txt
      - name: Tencent Cloud Code Analysis
        uses: TCATools/TCA-action@main
        with:
          block: false
          label: open-source
          from_file: changed.txt